### ISSUE TITLE
Command line fails with -r before --json

### ISSUE THREAD

**Issue by ope-nz** [RickStrahl/WestWindWebSurge#107]
Hi Rick, another minor issue.

This command fails to run with no error (this is as per the documentation);

WebSurgeCli.exe Test.websurge -s10 -t5 -d0 -r -y3 --json --outputFile Test.json

This works (note -r is at the end);

WebSurgeCli.exe Test.websurge -s10 -t5 -d0 -y3 --json --outputFile Test.json -r

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/6163217c-446c-4101-ac8e-f605ff85d1f3)

Documentation shows the first one which is the one that doesnt work

![image](https://github.com/RickStrahl/WestWindWebSurge/assets/26259049/41fbb0ee-ca64-428f-bbf9-8dac87b117a6)

**Comment by RickStrahl** [comment]
Sorry for the late response...

Finally looked into this and the problem is that the flag was not correctly configured and even when it did run would be ignored. I'm not sure why it was failing previously but it is working now in either position and... more importantly should actually randomize for both!
