### ISSUE TITLE
Confusing UX on first launch

### ISSUE THREAD

**Issue by alex-jitbit** [RickStrahl/WestWindWebSurge#113]
When lunching the program for the first time I'm presented with a request editing window. Data put into this request is not saved anywhere at all.

I went ahead and put request details and hit "Start test run". Nothing happened.

I then realized I first needed to click the little "+" button and THEN edit the request properties.

**Comment by RickStrahl** [comment]
Yes I agree - in fact I've run into this myself on a few occasions :smile:

I think what we want here is when a new project is created **or if a project is closed** we'll create an initial, empty entry with no label, so that when you 'just type a new url' it'll become the first entry.

Any additional urls however require clicking on the + to add (or alt-n).

**Comment by RickStrahl** [comment]
Updated in 3.0.0.19. 

It now shows an empty but selected request record that is immediately updated as you type a URL and/or request name.

Played around briefly with pre-setting the url and name with an arbitrary Web site and "New Request", but it seems cleaner to just leave blank and allow user to immediately enter a new request without having to 'clean up' first.

This is the same behavior you get from Close Session or New Session (which are actually the same operation but provided just for completeness).
