### ISSUE TITLE
Unclear what the -d Request per delay (0) is?

### ISSUE THREAD

**Issue by steveculshaw** [RickStrahl/WestWindWebSurge#20]
I'm unclear what the `-d Request per delay (0)` is?

Is this add a delay before each request?
I tried non-zero values from 1 to 100,000 and did see a delay on the first request, but not on subsequent calls

Could the help provide a bit more clarity on the usage?

**Comment by RickStrahl** [comment]
-d is like the DelayRequestMs setting in the UI. 0 means each thread gives up a CPU processing  slice (ie. a context switch), but there's not delay. -1 doesn't doesn't do any sort of delay or context switch. Any > 0 number will delay by that number of milliseconds. Really low numbers are likely to delay a little more due to .NET context switching.

-1 will be very CPU heavy on high volume tests. 0 will lighten the load on the CPU while still giving pretty close performance. Any non-zero value will introduce actual delays between requests.

**Comment by steveculshaw** [comment]
Blimey Rick ... talk about quick response !!!

Thanks for the response

Should you add the units to the help section, similar to the seconds mentioned in the `-s` and `-t` ?
