### ISSUE TITLE
Question: DataDriven Application

### ISSUE THREAD

**Issue by setiseeker** [RickStrahl/WestWindWebSurge#25]
Hi,

Do you have any guidelines / recommendations about using websurge in a data driven application.

My concern with load capturing traffic and then load testing with that traffic is that I have students, and student names need to be unique, after the first student is created the next calls to create a student will fail as the name is no longer unique.

How would I load test this scenario using WebSurge.

Thank you for a great tool.

**Comment by RickStrahl** [comment]
@setiseeker -  let me ask you how would you want it to work? I'm not really sure what the process would have to be in order to make this happen.

I think the only way you can test scenarios like this is to have a full sequence of events where you create a student, edit and then delete. WebSurge plays requests back by default in sequence so that scenario would work.

If you need to automate the data that you send into tests you can look into creating a .NET plug-in that can hook into request pipeline. You could look at each URL before it's processed and then create custom post/URL data as needed. Creating a plug-in is pretty easy to do.

Here's more info on the plug-in architecture and the events you can access:
https://github.com/RickStrahl/WestWindWebSurge/wiki/Creating-a-WebSurge-Plugin

**Comment by setiseeker** [comment]
Thank you for the reply.

Only way I can think it would work would be to capture a session, and when you view a request in that session that requires uniqueness, you can insert a place holder variable like {{RandomString}} or {{RandomInt}} and then that gets replaced with a randomly generated value.

This would need to work for both query strings and body content of the requests.

Looking at the provided link, I think I might be able to create a plugin to handle this for me.

thanks

**Comment by RickStrahl** [comment]
Let me know how it works out. I'm eager to provide some generic support, but frankly I have a hard time envisioning exactly how that should work. How would you map data from your data source to requests exactly for example?

**Comment by setiseeker** [comment]
I was thinking when capturing the session, when inputting data, I would use a specific string i.e. "STRINGRANDOM" in the input fields.

The using the plugin, I was thinking something along these lines:

 public class Randomiser : IWebSurgeExtensibility
    {
        public bool OnBeforeRequestSent(HttpRequestData data)
        {
            data.RequestContent = data.RequestContent.Replace("STRINGRANDOM", new Random().Next().ToString());

            LogString("AFTER:" + data.RequestContent);

            return true;
        }


The RequestContent does get updated with the new randon value in the input field, but this doesn't seem to work as the modified request doesn't get sent to the site during the load test. The original RequestContent gets sent during the load test. 

But I think its shows the concept I had in mind.

**Comment by RickStrahl** [comment]
Ok so I took a closer look and found that there's actually an issue in the timing of the plug-in code. Currently the code is firing after the request has already been created.

Adding a change so that the plug-in fires just before the request is created so that you get a chance to modify the content of the current request.

**Comment by RickStrahl** [comment]
Ok has been fixed and download has been updated. The code you've been running above should now work.

Added the following example to the Wiki topic as well:

```csharp
public bool OnBeforeRequestSent(HttpRequestData data)
{
    var header = new HttpRequestHeader
    {
        Name = "x-request-time",
        Value = DateTime.UtcNow.ToString("o")
    };
    data.Headers.Add(header);


    if (!string.IsNullOrEmpty(data.RequestContent))
    {
        // do something here to get your unique value
        var userId = new Random().Next().ToString();

        // then embed it into the content
        data.RequestContent = data.RequestContent.Replace("##UserId##", "USER_" + userId);
    }

    return true;
}
```

https://github.com/RickStrahl/WestWindWebSurge/wiki/Creating-a-WebSurge-Plugin

**Comment by setiseeker** [comment]
Hi Rick,

that's great news. Will test and give feedback.

Thanks for the great assistance.
