### ISSUE TITLE
Saving results to UNC drive locks UI

### ISSUE THREAD

**Issue by stephenpatten** [RickStrahl/WestWindWebSurge#27]
Every time I save the results of a test, no matter the size of the file, the UI freezes and then becomes unusable and must be killed through task manager.

**Comment by RickStrahl** [comment]
@stephenpatten How big is the result? The issue is that the data written out can be rather massive and so it might take quite a while. Can you just verify that if you do a short capture that generates a smaller file that it still locks? It might just be that saving to UNC takes longer due to network overhead?

It's probably a good idea to offload writing to a separate thread and write in chunks so the UI doesn't free up.
