### ISSUE TITLE
Exporting results causes second copy of program to execute

### ISSUE THREAD

**Issue by stephenpatten** [RickStrahl/WestWindWebSurge#28]
If you save the results as websurge, then no matter what you choose when the massage box prompts you to view them or not, a second version is instanciated.

**Comment by RickStrahl** [comment]
Ugh - yes. That's a bug.

Caused by the fact that the file is saved as a .websurge file and that extension is mapped to WebSurge so it opens up a new instance. 

Going to have to think about how to fix that one... Maybe the better way to handle all these exports is to open the folder that the export was created in and let you decide how to open it rather than trying to open the files? Might be a better idea anyway because these files tend to be so large.

**Comment by RickStrahl** [comment]
Changed result display to opening Explorer with the file selected - you can then decide whether you want to open the file in your editor.
