### ISSUE TITLE
application crashes eacht time on startup

### ISSUE THREAD

**Issue by flori27** [RickStrahl/WestWindWebSurge#35]
Hi,

I've downloaded your application on your website to evaluate the tool. I've installed it successfully. When I run the application, it crashes immediately (over and over again).
![schermafbeelding 2017-02-09 om 16 26 32](https://cloud.githubusercontent.com/assets/5380015/22789856/9ffcdacc-eee4-11e6-8e64-20dc81314aa7.png)

**Comment by RickStrahl** [comment]
Sorry for the delay getting back. 

Can you take a look at the error log in **%appdata%\Roaming\West Wind WebSurge\WebSurgeErrors.log**? Anything in there? I suspect not because the crash you're seeing is a hard windows crash not an application error. You might have to look at the event log to perhaps see more info.

**Comment by jawn** [comment]
Same issue here.

And while **%appdata%\Roaming\West Wind WebSurge** exists, is does not contain the log file.

**Comment by jawn** [comment]
I can no longer reproduce the issue.

This was the error in the event viewer for the first launch, which failed:

Application: WebSurge.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

And

Faulting application name: WebSurge.exe, version: 1.2.0.0, time stamp: 0x58aaa2d6
Faulting module name: KERNELBASE.dll, version: 10.0.14393.479, time stamp: 0x582588e6
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process ID: 0x4644
Faulting application start time: 0x01d2a1655e5e405e
Faulting application path: C:\Program Files\West Wind WebSurge\WebSurge.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 17ac11a7-28c5-4e41-8da7-bdfc17950250
Faulting package full name: 
Faulting package-relative application ID:

**Comment by RickStrahl** [comment]
Ugh - that looks like a nasty Windows error during startup before any of the WebSurge code even fires (other than Main) as the code come from `Application.Run()`.

Not sure what to do about that unfortunately since this is likely a driver or OS interaction issue.

**Comment by mikepetersonccv** [comment]
@RickStrahl I was able to reproduce this or a similar issue.  For me, it was due to <system.net><connectionManagement> sections in WebSurge.exe.config.  Adding a <clear /> fixed it for me
`<connectionManagement>
      
	  <clear />
      <add address="*" maxconnection="200"/>        
    </connectionManagement>`

**Comment by RickStrahl** [comment]
Hmmm... can you check if there's an explicit setting in your `machine.config` just to verify? This value typically is not set - I don't see in any of the machine wide settings.

How the heck did you figure this out since the error or stack trace points at nothing of the sort...

Thanks for this - will add to the default config.

**Comment by SirCrispalot** [comment]
I had the exact same issue (and same stack trace) as @jawn.  The `<clear />` node was already present in the config file so didn't have the desired effect.

Rebooted my machine and it started working again.

**Comment by MikeDPeterson** [comment]
@RickStrahl I had started writing my own loadtester from scratch and ran into the same issue.  After I realized I didn't need to write my own, I tried websurge and had the same issue, and the connectionManagement tweak fixed it.
