### ISSUE TITLE
AppData\Roaming\West Wind WebSurge\html\_preview.html missing

### ISSUE THREAD

**Issue by rajBar** [RickStrahl/WestWindWebSurge#47]
Hello,
I am trying to test my asp.net MVC application. However I am getting an error:
13/02/2018 11:20:17 - Could not find a part of the path 'C:\Users\Gulraj\AppData\Roaming\West Wind WebSurge\html\_preview.html'.

I navigated to this directory through git bash and it seems that the HTML folder was never even created. I created this myself, and a new error amounted:
Template File doesn't exist: c:\users\gulraj\appdata\roaming\west wind websurge\html\requets.cshtml

I've uninstalled the application, deleted all files and re-installed but this has not helped.

Any advice please??

Thank you

**Comment by natenho** [comment]
I also had the same issue. It apparently occurs when you install WebSurge with another admin user. The folder AppData\Roaming\West WindSurge is created for the admin user instead of your current user.
In my case, I was logged as foobar under the domain and because of required privileges WebSurge needed to be installed as local admin (foobar.MACHINE).

Then, all the files under Roaming has incorrectly been copied to C:\Users\foobar**.MACHINE**\AppData\Roaming\West Wind WebSurge
instead of 
C:\Users\foobar\AppData\Roaming\West Wind WebSurge

Just copy the directory to workaround this issue.

**Comment by RickStrahl** [comment]
Hmmm... The install is definitely a per user installation so you have to be running as the same user as you installed the application. If you log on as another user the executable is still there, but the data folder is not.

**Comment by rajBar** [comment]
Hey guys. I got this working, so thank you!!
