### ISSUE TITLE
Multiple problems, load test not working

### ISSUE THREAD

**Issue by Xylotomous** [RickStrahl/WestWindWebSurge#56]
I'm not sure what the issue is but the program is not usable in my environment. Windows 10, latest, running against a web api app running locally through Visual Studio 2015.

Case 1. Load test doesn't do anything.
: Make session (entered URL and headers manually)
: URL appears in left column under Session tab
: Selecting TEST from the right under request tab will issue a single request. Get 200 response.
: Next attempting to start load test via START button (assuming threads are one per request? docs are unclear) using default value or using a higher thread value results in a handful of requests in output window, usually about 12. Other metrics output like number of requests, etc. are all zero. No charts are generated, the menu option is greyed out. No results of any kind, nothing.

Case 2. WebSurge fails completely on random requests with either Abort timeouts or Internal Server error "System Component failure" with long stacktrace having nothing to do with the app under test.
Issuing requests to the same URLs to the same running application (not restarted) in Fiddler returns proper 200 results. Fiddler was not running while using WebSurge.
**NOTE closed app, gave second try of runs and can't repeat these. Not sure what the issue was...

Case 3. The Help menu is broken. Select, click does nothing. Docs are available elsewhere but still...

Case 4. The Comment/suggestions menu goes to a 404 page.

I gave up at this point, not wanting to QA this program.

Not really a technical issue but the near instant nag screen made me write off using this app, even if it worked. I barely (I mean within 3 requests while learning the UI) used it when it popped up. And again every few requests. It also doesn't even count properly. First 5 times it was "zero" uses, then eventually "1" use. I never closed the program during all this. I understand wanting to get paid but give people a chance to try it for an hour even...

Finally, please know I'm not one to rant every chance I get, denigrating others work. This is a legitimate bug report for something that is a weird outlier case I'm guessing because I can't believe the program is really this buggy.

**Comment by RickStrahl** [comment]
Fair enough.

But it sure seems that something was happening with your connection settings that were essentially blocking or hanging requests. A proxy perhaps? If Fiddler was attached (or maybe disconnected while WS was already running so the proxy settings would have changed) you might see some funky behavior with requests not going through.

If that's the case that would affect both items 1 and 2.

As to the nag screen - not sure. It's not supposed to be popping up frequently especially not on early usage. I have to actually look at the code for that but the way it's supposed to work is after a largish number of uses the nag screen gets more frequent, but if you are just starting to try this out this shouldn't even be happening at all. I'll take a look.

To be honest this app has been sitting idle for quite a while so it definitely needs some updates - some of the missing bits are bad links that have changed on the Web site since last updates. I fixed the help file links (which should point to the Web docs now - the problem is that the CHM viewer no longer works in recent Windows 10 builds when popped up from within applications).  That at least is fixed.

Anyway - I appreciate the feedback especially when getting frustrated like this.

Aloha.
