### ISSUE TITLE
Headers in Request tab do not seem to update when I change them

### ISSUE THREAD

**Issue by gregpakes** [RickStrahl/WestWindWebSurge#66]
I am not quite sure of replication steps, but I there is a bug somewhere.

I am pasting headers (specifically cookies) into the Request tab.  These work great first time, but when the auth cookie expires and I paste a new cookie in, it does not get picked up.  The request is sent with the old cookie. 

I have to close WebSurge and reopen, then paste.  Then it will work.

**Comment by RickStrahl** [comment]
Where are you pasting the cookie? Into the request or the Session options?

If you're using Auth cookies I recommend you paste it into the `ReplaceCookieValue` field in the property sheet as that will be applied to all requests. If there's already a cookie there it will be replaced with that one.

If you are pasting the cookie into the request data then there's probably a focus bug where the content isn't saved. There's focus check code on all fields, so in theory that value should always take. 

Make sure you have the latest version - there were a few fixes in recent updates that relate to that issue and I haven't seen any issues with that anymore (there were before). 

If that still happens with the latest version, let me know if you can find a repeatable scenario. Pay close attention where you click or tab to after entering the data when it fails - that might give a clue.

Part of this issue is an old Windows bug that doesn't fire focus events when clicking interacting with toolbars. I have gate code in the toolbar access logic, but there may still be some holes (maybe hotkeys?) that may end up not saving the input.

**Comment by gregpakes** [comment]
Thanks for the detailed reply.

Quick answers as I’m not at computer.

I am paying into the Request Tab, then clicking Test.

I am definitely on the latest version.

**Comment by RickStrahl** [comment]
Ah yes that might be the issue! There is no focus change and the binding isn't updating. 

Should be an easy fix.

If you're updating cookies - use the ReplaceCookieValue, or you can turn on the auto cookie capture.

**Comment by gregpakes** [comment]
Thanks - I’ll do that from now on.
