### ISSUE TITLE
Sessions with RequestTimeoutMs lower than 1000 fails 

### ISSUE THREAD

**Issue by Spica92130** [RickStrahl/WestWindWebSurge#71]
Hi,

 RequestTimeoutMs = 999 -> all requests session fails
 RequestTimeoutMs=1000 -> all requests succeeded.

This can easily be seen by setting timeout lower than 1000 and using TEST button. This leads to 
CheckSite Error: Timeout can be only be set to 'System.Threading.Timeout.Infinite' or a value > 0. Parameter name: value

Regards

**Comment by RickStrahl** [comment]
Fixed. 

Switched behavior to use Milliseconds instead of seconds with a new configuration switch:

![image](https://user-images.githubusercontent.com/1374013/110878251-f0a88c00-827e-11eb-8865-671fe8a5de5a.png)

This value can go all the way down to 10ms. Note that timeout errors can sometimes turn up as response read errors so the error message may not always be clear or even precisely repeatable, so you'll do well setting a timeout that does not get triggered often or you may end up with misleading errors (basically connection has been closed errors which occur after initial bytes are retrieved but while the response is downloading. This is especially prescient when the request timeout is very short.

Some quick testing shows for me I can get down to about 50ms before I see issues even with local content failing randomly due to the timeouts.
