### ISSUE TITLE
Allowing websurge to run load test for Azure app

### ISSUE THREAD

**Issue by fariskarcic** [RickStrahl/WestWindWebSurge#78]
Hi,

I have this .NET Core Web API application running in Azure cloud which I want to load test.
I successfully done it locally, but when I tried to do it for cloud env Websurge gave me info to place "websurge-allow.txt" to root of site. So I created it inside "wwwroot" folder on server, however Websurge still warns me that I have to add it. So it doesnt recognize it.
If it's any info Web API uses Azure AD authN & authZ via Bearer token.

Any help on this?

Thanks in advance.

**Comment by fariskarcic** [comment]
Alright I've figured out a way around this.
Just create endpoint which has route "/websurge-allow.txt" and returns Ok().

Cheers.

**Comment by RickStrahl** [comment]
What type of project are you running? Putting `websurge-allow.txt` into `wwwroot` in an Core Web project should work. 

👍 for an explicit end-point. That works too, but still surprised that this is necessary. You might check and see what `HostingEnvironment.WebRoot` holds in your project when it runs on Azure (and in dev) - does the file also not work in local dev when you use an explicit domain name?

**Comment by RickStrahl** [comment]
Another thought here - the reason this probably wasn't working in your API project is that in order to serve static files the static file middleware has to be present.

So the workarounds are:

* Make sure that app.UseStaticFiles() is in app then add the physical file
* Add an explicit endpoint as you mentioned above and just return a string
