### ISSUE TITLE
Capture Session For Post Requests And No Data

### ISSUE THREAD

**Issue by hammad-awan** [RickStrahl/WestWindWebSurge#81]
Hello,

It appears that if one uses the capture session functionality and a post occurs without sending any data, i.e., a content length of zero, the request fails because there is no content-length of 0 specified in the request header.

The UI also will not allow a post to occur with a content-length of 0 explicitly set in the header and no data. If some data is put into the content body, then the request will work.

Yes, I know a get should be used for a request without any data posted, but I didn't write the post requests without a body in them. I'm just relaying the issue.

Thanks.

**Comment by RickStrahl** [comment]
Fixed.

Problem is the base system HTTP library (HttpWebRequest in this case) automatically sets content length, but doesn't if there's nothing assigned resulting in the missing value. Added check code for empty POST and PUT requests and in that case explicitly set the ContentLength to 0. This works and the request now goes through with no body. Fixed in `westwind.utilities` package.
