### ISSUE TITLE
Object reference not set to an instance of an object on clicking Test

### ISSUE THREAD

**Issue by amitdhakre13** [RickStrahl/WestWindWebSurge#84]
Logs attached: [WebSurgeErrors.log](https://github.com/RickStrahl/WestWindWebSurge/files/6472388/WebSurgeErrors.log)

Steps:
1. Open WebSurge
2. Enter Url in the request tab
3. Click on Test

**Comment by RickStrahl** [comment]
Hmmm... seems to be happening because at that point there's no actual request yet. Definitely a bug - regression as this worked before...

The work around is to click on `New Request` first, then add the request, then click in the tree to select. From then on everything works as it should. It's the first test before anything that is selected is causing the problem.

Thanks.
