### ISSUE TITLE
feature request - no way to enter the data manually in the Request editor

### ISSUE THREAD

**Issue by mboxraj** [RickStrahl/WestWindWebSurge#92]
Ability to manually add binaries or files in editor for file upload requests.

**Comment by RickStrahl** [comment]
Started working on this yesterday. There will be a toggle view that lets you enter form data interactively. Separate view that shows the form fields in a list including the ability to add files.

The best way to capture multi-part form variables would be to capture request in the Capture tool, but that is unfortunately [broken in the WebView2 control for which I have an outstanding bug report](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2162). Hopefully this can be fixed in the WebView2 control which would greatly simplify this process more interactively.

**Comment by RickStrahl** [comment]
So I've added an interactive editor that can be toggled between the standard text based edit box, or a new form editor. The form editor is interactive and allows for adding file data. The editor is two-way so you can toggle back and forth.

Binary content is created and stored in the raw `RequestContent` with a `b64_` prefix in front of a base64 encoded string. At runtime the data is converted a byte stream and sent out.

Here's the base64 data in the basic request text editor:

![image](https://user-images.githubusercontent.com/1374013/155053152-5c2de29e-f40a-4b28-9abc-dbc8b802028e.png)

and here's the interactive editor with the same data:

![image](https://user-images.githubusercontent.com/1374013/155053211-5aaa82bf-270f-4c0a-b9f4-d7edc1dfc89b.png)

You can toggle between view modes using the icon, context menu or ctrl-t shortcut.

Still need some additional testing for actual using this data, but at least we can get the data in.

On a side note it looks like the capture bug has been accepted and so hopefully in the not so distant future we'll see an update in the WebView control that can capture binary content.

**Comment by mboxraj** [comment]
Thanks Rick

Warm Regards
rajesh
